clear; clc; close all;
%% figure5(a) 
delta1=1;
alphaL = pi/6;
alphaR = pi;
delta2=2;
dLD = delta2;
dLU = delta2;

d1D = delta1;   
d1U = delta1;  
t1L =   0; t2L =2;
t1R =  -1; t2R =4;
epsD = delta1 * t1R / delta2;
epsU = -epsD;
tol =  1e-10;

N_dRD = 1001; 
N_dRU = 1001;
dRD_list = linspace(-12, 12, N_dRD)+ 1e-9;     
dRU_list = linspace(-12, 12, N_dRU)+ 1e-9;    
[dRD_grid, dRU_grid] = meshgrid(dRD_list, dRU_list);

denomL = t1L*t2L - dLD*dLU;
denomR = t1R*t2R - dRD_grid.*dRU_grid;  
r = (denomR ./ denomL).^(1/4);
p1 = 2 .* r.^2 .* ( t1L*exp(1i*alphaL)*t2L*exp(-1i*alphaL) - dLD*dLU);
p2 = - t2R*exp(-1i*alphaR) * t1L*exp(1i*alphaL) ...
     - t1R*exp(1i*alphaR) * t2L*exp(-1i*alphaL) ...
     + dLU*dRD_grid + dRU_grid*dLD;
Xe = -p2 ./ p1;

eD = epsD; eU = epsU;
wR = dRD_grid .* d1U + dRU_grid .* d1D ...
     - eD * t1R * exp(alphaR * 1i) ...
     - t2R * exp(-1i * alphaR) * eU;

tauR = t2R * exp(-1i * alphaR) + t1R * exp(alphaR * 1i);
wL = dLU*d1D + d1U*dLD ...
     - eD * t1L * exp(alphaL * 1i) ...
     - eU * t2L * exp(-1i * alphaL);
tauL = t2L * exp(-1i * alphaL) + t1L * exp(alphaL * 1i);

T = (p2.^2 - p1.^2) ./ p1;
lam0 = -T - (tauR * tauL) .* p2 ./ p1 ...
       - 0.5 .* r.^2 .* tauL^2 ...
       - 0.5 .* tauR^2 ./ r.^2;

lam1 = (eU + eD) .* T ...
       - (tauL .* wR + tauR .* wL) .* p2 ./ p1 ...
       - wR .* tauR ./ r.^2 ...
       - wL .* tauL .* r.^2;

lam2 = (d1D*d1U - eD*eU) .* T ...
       - wL .* wR .* p2 ./ p1 ...
       - 0.5 .* wR.^2 ./ r.^2 ...
       - 0.5 .* wL.^2 .* r.^2;

discE = lam1.^2 - 4.*lam0.*lam2;
sumR = t2R*exp(-1i*alphaR) + t1R*exp(1i*alphaR);
sumL = t2L*exp(-1i*alphaL) + t1L*exp(1i*alphaL);

a0 = -(t1L*exp(alphaL*1i) - t2L*exp(-1i*alphaL))^2 - 4*dLD*dLU;
a1 = -2*(d1D*dLU + d1U*dLD)*tauL ...
     + (epsU + epsD)*(-2*t1L*t2L + 4*dLD*dLU) ...
     + 2*t2L^2 * exp(-1i*alphaL)^2 * epsU ...
     + 2*epsD * t1L^2 * exp(alphaL*1i)^2;

a2 = -exp(alphaL*1i)^2 * t1L^2 * epsD^2 ...
     - t2L^2 * exp(-1i*alphaL)^2 * epsU^2 ...
     + (d1D*dLU + d1U*dLD) * (2*epsU*t2L*exp(-1i*alphaL) + 2*epsD*t1L*exp(alphaL*1i)) ...
     + dLD*dLU * (2*d1D*d1U - 4*epsD*epsU + 4*p2) ...
     + t1L*t2L * (-4*d1D*d1U + 2*epsD*epsU - 4*p2) ...
     - d1D^2 * dLU^2 ...
     - dLD^2 * d1U^2;


W1_fun = @(x) x + sqrt(x.^2 - 1);
W2_fun = @(x) x - sqrt(x.^2 - 1);
Wfun = @(x) max(abs(W1_fun(x)), abs(W2_fun(x)));
WXe = Wfun(Xe);


E1 = (-lam1 + sqrt(discE)) ./ (2.*lam0);
B1 = ( (sumR.*E1 + wR) .* (sumL.*E1 + wL) ) ./ p1.^2 - 1;
C1 = - ( (E1.^2.*a0 + E1.*a1 + a2).*r.^4 - (sumR.*E1 + wR).^2 ) ./ (2.*r.^2.*p1.^2);
discY1 = (B1.*Xe - C1).^2 - 4.*C1.*Xe.^3;
Yp1 = (B1.*Xe - C1 + sqrt(discY1)) ./ (2.*Xe.^2);
Ym1 = (B1.*Xe - C1 - sqrt(discY1)) ./ (2.*Xe.^2);
Wm_YZ1 = max(Wfun(Yp1), Wfun(Ym1));
cond_E1 = (Wm_YZ1 - WXe) <= 1e-9; 


E2 = (-lam1 - sqrt(discE)) ./ (2.*lam0);
B2 = ( (sumR.*E2 + wR) .* (sumL.*E2 + wL) ) ./ p1.^2 - 1;
C2 = - ( (E2.^2.*a0 + E2.*a1 + a2).*r.^4 - (sumR.*E2 + wR).^2 ) ./ (2.*r.^2.*p1.^2);
discY2 = (B2.*Xe - C2).^2 - 4.*C2.*Xe.^3;
Yp2 = (B2.*Xe - C2 + sqrt(discY2)) ./ (2.*Xe.^2);
Ym2 = (B2.*Xe - C2 - sqrt(discY2)) ./ (2.*Xe.^2);
Wm_YZ2 = max(Wfun(Yp2), Wfun(Ym2));
cond_E2 = (Wm_YZ2 - WXe) <= 1e-9; 


phase_map = zeros(size(dRD_grid)); 
phase_map(cond_E1 & ~cond_E2) = 1; 
phase_map(~cond_E1 & cond_E2) = 2; 
phase_map(cond_E1 & cond_E2)  = 3; 


fig5 = figure('Position', [120, 80, 980, 1080], 'Color', 'w');
ax_phase = axes('Parent', fig5, 'Position', [0.085, 0.705, 0.385, 0.245]);
ax_E     = axes('Parent', fig5, 'Position', [0.605, 0.705, 0.330, 0.245]);
ax_beta  = axes('Parent', fig5, 'Position', [0.085, 0.405, 0.850, 0.225]);
ax_M     = axes('Parent', fig5, 'Position', [0.085, 0.095, 0.850, 0.225]);
hold(ax_phase, 'on');

imagesc(ax_phase, dRD_list, dRU_list, phase_map);
set(ax_phase, 'YDir', 'normal'); 

contour(ax_phase, dRD_list, dRU_list, double(cond_E1), [0.5 0.5], 'r-', 'LineWidth', 1.5);
contour(ax_phase, dRD_list, dRU_list, double(cond_E2), [0.5 0.5], 'b-', 'LineWidth', 1.5);

colormap(ax_phase, [1 1 1;       
                    1 0.75 0.75; 
                    0.75 0.82 1; 
                    0.75 1 0.75]);
set(ax_phase, 'CLim', [-0.5, 3.5]); 

xlabel(ax_phase, '$\delta_{RD}$', 'Interpreter', 'latex', 'FontSize', 14);
ylabel(ax_phase, '$\delta_{RU}$', 'Interpreter', 'latex', 'FontSize', 14);
xlim(ax_phase, [-12 12]);
ylim(ax_phase, [-12 12]);
cb_phase = colorbar(ax_phase);
cb_phase.Position = [0.480, 0.705, 0.022, 0.245];
cb_phase.Ticks = [0, 1, 2, 3]; 
cb_phase.TickLabels = {'Trivial', '$E_1$', '$E_2$', '$E_1,E_2$'};
cb_phase.TickLabelInterpreter = 'latex';
cb_phase.FontSize = 14;
cb_phase.Ruler.TickLabelRotation = 90;

grid(ax_phase, 'on');
axis(ax_phase, 'tight');ax = ax_phase;
box(ax_phase, 'on');
ax.LineWidth = 1;
ax.XColor = 'k';
ax.YColor = 'k';
box(ax_phase, 'on');
text(ax_phase, -0.20, 1.04, '(a)', 'Units', 'normalized', ...
    'Interpreter', 'latex', 'FontSize', 18, 'Color', 'k');
text(ax_phase, 0.52, 0.42, '$\times$', 'Units', 'normalized', ...
    'Interpreter', 'latex', 'FontSize', 18, 'Color', 'r', ...
    'HorizontalAlignment', 'center');

clc;
N = 30; L = 2*N;
delta1=1;
alphaL = pi/6;
alphaR = pi;
delta2=2;
dLD = delta2;
dLU = delta2;
d1D = delta1;   
d1U = delta1;  
t1L =  0; t2L =2;
t1R =  -1; t2R =4;
epsD = delta1 * t1R / delta2;
epsU = -epsD;
dRD=0.4; dRU=-3;

%% Numerical OBC 
ao = zeros(1,L); ao(1:2:end)=epsU; ao(2:2:end)=epsD;
a1u = zeros(1,L-1); a1u(1:2:end)=d1U; a1u(2:2:end)=dLD; 
a1d = zeros(1,L-1); a1d(1:2:end)=d1D; a1d(2:2:end)=dRU;
a2u = zeros(1,L-2); a2u(1:2:end)=t1L*exp(alphaL*1i); a2u(2:2:end)=t2L*exp(-1i*alphaL);
a2d = zeros(1,L-2); a2d(1:2:end)=t1R*exp(alphaR*1i); a2d(2:2:end)=t2R*exp(-alphaR*1i);
a3u = zeros(1,L-3); a3u(1:2:end)=dLU; a3u(2:2:end)=0;
a3d = zeros(1,L-3); a3d(1:2:end)=dRD; a3d(2:2:end)=0;
H = diag(ao,0) + diag(a1u,1) + diag(a1d,-1) + diag(a2u,2) + diag(a2d,-2) + diag(a3u,3) + diag(a3d,-3);
[V, D1] = eig(H);
EE = diag(D1);          
epsilon = 1e-8; 
real_rounded = round(real(EE)/epsilon) * epsilon; 
[~, ind1] = sortrows([real_rounded, imag(EE)], [1, 2]); 
eNum = EE(ind1);         
vecNum = V(:, ind1);
%% PBC 
M1 = 6000;                    
kA = linspace(-pi, pi, M1);
kB = linspace(pi, 3*pi, M1);
klist = [kA, kB(2:end)];        
idxMid = M1;                   
Etrk = zeros(2, numel(klist));
for j = 1:numel(klist)
    k = klist(j);
    beta = exp(1i*k);

    HkU = [ ...
        epsU + t1R*exp( 1i*alphaR)/beta + beta*t1L*exp( 1i*alphaL), ...
        d1U + dRU/beta + beta*dLU; ...
        d1D + dRD/beta + beta*dLD, ...
        epsD + t2R*exp(-1i*alphaR)/beta + beta*t2L*exp(-1i*alphaL) ...
    ];

    ev = eig(HkU);

    if j == 1
        [~, idx0] = sort(real(ev));
        Etrk(:,j) = ev(idx0);
    else
        prev = Etrk(:,j-1);

        cand1 = ev;
        cand2 = ev([2,1]);

        cost1 = abs(cand1(1)-prev(1)) + abs(cand1(2)-prev(2));
        cost2 = abs(cand2(1)-prev(1)) + abs(cand2(2)-prev(2));

        if cost1 <= cost2
            Etrk(:,j) = cand1;
        else
            Etrk(:,j) = cand2;
        end
    end
end
sameCost = abs(Etrk(1,idxMid)-Etrk(1,1)) + abs(Etrk(2,idxMid)-Etrk(2,1));
swapCost = abs(Etrk(1,idxMid)-Etrk(2,1)) + abs(Etrk(2,idxMid)-Etrk(1,1));

if swapCost < sameCost
   
    EPBC1 = [Etrk(1,1:idxMid), Etrk(2,idxMid+1:end)];
    EPBC2 = [Etrk(2,1:idxMid), Etrk(1,idxMid+1:end)];
else
    
    EPBC1 = Etrk(1,1:idxMid);
    EPBC2 = Etrk(2,1:idxMid);
end
EPBC1_plot = break_large_jumps(EPBC1, 30);
EPBC2_plot = break_large_jumps(EPBC2, 30);

%%GBZ
M_full = 1200; 
theta_all = linspace(0, 2*pi, M_full + 2);  
theta0    = theta_all(2:end-1);
M         = numel(theta0);
z_branch    = NaN(8, M);
first_valid = false;   
GBZ_points = []; 
E_points = [];  
M_GBZ = [];

get_p_beta = @(E) [ ...
    (t1L*t2L - dLD*dLU), ...
    (-t2L*(E-epsU)*exp(-1i*alphaL) - t1L*(E-epsD)*exp(1i*alphaL) - d1U*dLD - d1D*dLU), ...
    (exp(-1i*(alphaL-alphaR))*t1R*t2L + exp(1i*(alphaL-alphaR))*t1L*t2R + E^2 + (-epsD-epsU)*E - d1D*d1U - dLD*dRU - dLU*dRD + epsU*epsD), ...
    (-t2R*(E-epsU)*exp(-1i*alphaR) - t1R*(E-epsD)*exp(1i*alphaR) - d1U*dRD - d1D*dRU), ...
    (t1R*t2R - dRD*dRU) ...
];

for j = 1:numel(theta0)
    theta = theta0(j);
    g8 = -( ...
        exp(1i*5*theta) * ( t1L^2 * exp(1i*2*alphaL) + t2L^2 * exp(-1i*2*alphaL) ) ...
        + dLD*dLU * exp(1i*4*theta) * ( exp(1i*theta) + 1 )^2 ...
        - t2L*t1L * exp(1i*4*theta) * ( 1 + exp(1i*2*theta) ) ...
        ) ...
        * ( t2L*t1L - dLD*dLU ) ...
        * ( exp(1i*theta) - 1 )^2;

    g7 = -(t2L*t1L - dLD*dLU) ...
        * ( - t2L*(epsU-epsD)*exp(-1i*alphaL) + t1L*(epsU-epsD)*exp(1i*alphaL) ...
            + 2*d1U*dLD + 2*d1D*dLU ) ...
        * (exp(1i*theta)-1)^2 * (exp(1i*theta)+1) * exp(1i*4*theta);

    g6 = -(t2L*t1L - dLD*dLU) ...
          * exp(1i*3*theta) ...
          * ( t1L*exp(1i*alphaL) + t2L*exp(-1i*alphaL) ) ...
          * ( t1R*exp(1i*alphaR) + t2R*exp(-1i*alphaR) ) ...
          * ( exp(1i*2*theta) - 1 )^2 ...
        - 2 * exp(1i*(5*theta + alphaL + alphaR)) * t1L^2 * t1R * t2L ...
        + (d1U*dLD + d1D*dLU) * (epsD - epsU) * (exp(1i*theta) - 1)^2 ...
          * ( -t1L*exp(1i*alphaL) + t2L*exp(-1i*alphaL) ) * exp(1i*4*theta) ...
        + (d1D*d1U + dLD*dRU + dLU*dRD) * (exp(1i*theta) - 1)^2 ...
          * ( -t2L^2*exp(-1i*2*alphaL) - t1L^2*exp(1i*2*alphaL) ) * exp(1i*4*theta) ...
        + (4*t1L*t1R*t2L^2 - 2*t1R*t2L*dLD*dLU) * (exp(1i*theta) - 1)^2 ...
          * exp(1i*(4*theta - alphaL + alphaR)) ...
        + (4*t1L^2*t2L*t2R - 2*t1L*t2R*dLD*dLU) * (exp(1i*theta) - 1)^2 ...
          * exp(1i*(4*theta + alphaL - alphaR)) ...
        + (3*t1L*t2L^2*t2R - 2*t2L*t2R*dLD*dLU) * exp(1i*(4*theta - alphaL - alphaR)) ...
          * (exp(1i*theta) - 1)^2 ...
        + t1L^3*t2R * exp(1i*(4*theta + 3*alphaL - alphaR)) * (exp(1i*theta) - 1)^2 ...
        - ( ...
            2*( dLD*dRU + dLU*dRD + d1D*d1U + (epsD - epsU)^2/2 ) * t2L*t1L ...
            - (d1U*dLD + d1D*dLU)^2 ...
          ) * (exp(1i*theta) - 1)^2 * exp(1i*4*theta) ...
        + ( ...
            3*t1L^2*t2L*(exp(1i*theta) - 1)^2 ...
            + 2*t1L^2*exp(1i*theta)*t2L ...
            - 2*t1L*dLD*dLU*(exp(1i*theta) - 1)^2 ...
            + t2L^3*(exp(1i*theta) - 1)^2 / (exp(1i*alphaL)^4) ...
          ) * exp(1i*alphaR) * (exp(1i*theta))^4 * t1R * exp(1i*alphaL);

    g5 = ( ...
        -(d1U*dRD + d1D*dRU) ...
          * ( t2L^2*exp(-1i*2*alphaL) + t1L^2*exp(1i*2*alphaL) ) ...
        - dLD*dLU * t2R * (epsD - epsU) * exp(-1i*alphaR) ...
        + (epsD - epsU) ...
          * ( -t1L^2*t2R*exp(1i*(2*alphaL - alphaR)) ...
              + t2L^2*t1R*exp(1i*(-2*alphaL + alphaR)) ) ...
        - dLD*dLU ...
          * ( -t1R*(epsD - epsU)*exp(1i*alphaR) + 2*d1U*dRD + 2*d1D*dRU ) ...
        + (d1U*dLD + d1D*dLU) ...
          * ( t1L*t2R*exp(1i*( alphaL - alphaR)) ...
              + t1L*t1R*exp(1i*( alphaL + alphaR)) ...
              + t2L*t1R*exp(1i*(-alphaL + alphaR)) ...
              + t2L*t2R*exp(1i*(-alphaL - alphaR)) ) ...
        ) ...
        * (exp(1i*theta) - 1)^2 ...
        * (exp(1i*theta) + 1) ...
        * exp(1i*3*theta);

    g4 =  (2 * (exp(1i*theta) - 1)^2 * ( dLD*dRU + dLU*dRD + d1D*d1U + (epsD - epsU)^2/2 ) ...
          * ( exp(1i*( alphaL - alphaR)) * t1L * t2R + exp(1i*(-alphaL + alphaR)) * t1R * t2L ) ...
        + (d1U*dLD + d1D*dLU) * (epsD - epsU) * (exp(1i*theta) - 1)^2 ...
          * (t1R * exp(1i*alphaR) - t2R * exp(-1i*alphaR)) ...
        + (epsD - epsU) * (d1U*dRD + d1D*dRU) * (exp(1i*theta) - 1)^2 ...
          * (-t2L * exp(-1i*alphaL) + t1L * exp(1i*alphaL) ) ...
        + 2 * (exp(1i*theta) - 1)^2 ...
          * (d1D*d1U + dLD*dRU + dLU*dRD) ...
          * (exp(1i*( alphaL + alphaR)) * t1R * t1L + exp(1i*(-alphaL - alphaR)) * t2L * t2R ) ...
        + (-3*t2R*t1R + dRD*dRU) * (exp(2i*theta) + 1) * (t1L^2 * exp(2i*alphaL) + t2L^2 * exp(-2i*alphaL)) ...
        - dLD*dLU * (t1R^2 - 1) * (t1R^2 * exp(2i*alphaR) + t2R^2 * exp(-2i*alphaR)) * (exp(2i*theta) + 1) ...
         + (t1R^2 * dLD * dLU - 3*t1L*t2L) * (exp(2i*theta) + 1)  * ( t1R^2 * exp(2i*alphaR) + t2R^2 * exp(-2i*alphaR) ) ...
     - dLD*dLU * (t1R^2 - 1) * ( t1R^2 * exp(2i*alphaR) + t2R^2 * exp(-2i*alphaR) ) * (exp(2i*theta) + 1)) * exp(3i*theta) ...
        + t2R^2 * (t2L*t1L - dLD*dLU) ...
          * (exp(4i*theta) + 1) * exp(2i*(theta - alphaR)) ...
        + t1R^2 * (t2L*t1L - dLD*dLU) ...
          * exp(2i*(theta + alphaR)) * (exp(4i*theta) + 1) ...
        - t1L^2 * (-t2R*t1R + dRD*dRU) ...
          * exp(2i*(theta + alphaL)) * (exp(4i*theta) + 1) ...
        - t2L^2 * (-t2R*t1R + dRD*dRU) ...
          * exp(2i*(theta - alphaL)) * (exp(4i*theta) + 1) ...
        - 2 * exp(1i*(3*theta - 2*alphaL + 2*alphaR)) ...
          * t1R^2 * t2L^2 * (exp(2i*theta) + 1) ...
        - 2 * exp(1i*(3*theta + 2*alphaL - 2*alphaR)) ...
          * t1L^2 * t2R^2 * (exp(2i*theta) + 1) ...
        + 4 * t2L * t1L ...
          * ( t1R^2 * exp(2i*(2*theta + alphaR)) ...
            + t2R^2 * exp(2i*(2*theta - alphaR)) ) ...
        + 4 * t2R * t1R ...
          * ( t2L^2 * exp(2i*(2*theta - alphaL)) ...
            + t1L^2 * exp(2i*(2*theta + alphaL)) ) ...
        + (( 2*t1R*t2R*dLU - 2*dRD*d1U^2 - 2*dRU*d1D*d1U ) * dLD ...
            + ( -2*d1D*d1U*dRD - 2*d1D^2*dRU ) * dLU ...
            + 2*t2L * (-4*t2R*t1R + dRD*dRU) * t1L ...
          ) * (exp(2i*theta) + 1) * exp(3i*theta) ...
        + 4 * exp(2i*(2*theta - alphaL + alphaR)) * t1R^2 * t2L^2 ...
        + 4 * exp(2i*(2*theta + alphaL - alphaR)) * t1L^2 * t2R^2 ...
        + ( ...
            ( (-4*t2R*t1R + 4*dRD*dRU) * dLU ...
              + 4*dRD*d1U^2 + 4*dRU*d1D*d1U ) * dLD ...
            + ( 4*d1D*d1U*dRD + 4*d1D^2*dRU ) * dLU ...
            - 4*t2L * (-3*t2R*t1R + dRD*dRU) * t1L ...
          ) * exp(4i*theta)... 
        + 2 * (exp(2i*theta) + exp(6i*theta)) * (t1L*t1R*t2L*t2R - dLD*dLU*dRD*dRU);

    g3 = ( ...
        (d1U*dRD + d1D*dRU) * ( ...
            exp(1i*(-alphaL + alphaR)) * t1R * t2L ...
          + exp(1i*(-alphaL - alphaR)) * t2L * t2R ...
          + exp(1i*( alphaL - alphaR)) * t1L * t2R ...
          + exp(1i*( alphaL + alphaR)) * t1R * t1L ...
        ) ...
        + (d1U*dLD + d1D*dLU) * ( ...
            - t2R^2 * exp(-2i*alphaR) ...
            - t1R^2 * exp( 2i*alphaR) ...
        ) ...
        - (epsD - epsU) * ( ...
            t1R^2 * t2L * exp(1i*(-alphaL + 2*alphaR)) ...
          - t1L * t2R^2 * exp(1i*( alphaL - 2*alphaR)) ...
        ) ...
        - 2 * dRU * dRD * (d1U*dLD + d1D*dLU) ...
        + dRU * (epsD - epsU) * dRD * ( ...
            - t2L * exp(-1i*alphaL) ...
            + t1L * exp( 1i*alphaL) ...
        ) ...
        ) ...
        * (exp(1i*theta) - 1)^2 ...
        * (exp(1i*theta) + 1) ...
        * exp(2i*theta);

    g2 = (exp(1i*theta) - 1)^2 * exp(2*1i*theta) * ...
         ( exp(1i*(-alphaL + 3*alphaR)) * t1R^3 * t2L ...
         + exp(1i*( alphaL - 3*alphaR)) * t1L * t2R^3 ) ...
       - exp(2*1i*theta) * (d1U*dRD + d1D*dRU) * (epsD - epsU) * (exp(1i*theta) - 1)^2 * ...
         ( t1R * exp(1i*alphaR) - t2R * exp(-1i*alphaR) ) ...
       - 2 * exp(2*1i*theta) * (-2*t2R*t1R + dRD*dRU) * ...
         (exp(2*1i*theta) - exp(1i*theta) + 1) * ...
         ( exp(1i*(-alphaL - alphaR)) * t2L * t2R ...
         + exp(1i*(-alphaL + alphaR)) * t1R * t2L ) ...
       - exp(2*1i*theta) * (exp(1i*theta) - 1)^2 * ...
         (d1D*d1U + dLD*dRU + dLU*dRD) * ...
         ( t1R^2 * exp(2*1i*alphaR) + t2R^2 * exp(-2*1i*alphaR) ) ...
       - 2 * exp(2*1i*theta) * (-2*t2R*t1R + dRD*dRU) * ...
         (exp(2*1i*theta) - exp(1i*theta) + 1) * ...
         ( exp(1i*(alphaL - alphaR)) * t1L * t2R ...
         + exp(1i*(alphaL + alphaR)) * t1R * t1L ) ...
       + (exp(4*1i*theta) + 1) * (-t2R*t1R + dRD*dRU) * ...
         ( t2L*t2R * exp(1i*(theta - alphaL - alphaR)) ...
         + t1L*t2R * exp(1i*(alphaL - alphaR + theta)) ...
         + t1L*t1R * exp(1i*(theta + alphaL + alphaR)) ...
         + t1R*t2L * exp(1i*(-alphaL + alphaR + theta)) ) ...
       - t2R^2 * ...
         ( t1R*t2L * exp(1i*(2*theta - alphaL - alphaR)) ...
         + 2 * exp(1i*(3*theta + alphaL - alphaR)) * t1L * t1R ...
         + t2L * exp(1i*(4*theta - alphaL - alphaR)) * t1R ) ...
       - t1R^2 * ...
         ( t2R*t1L * exp(1i*(2*theta + alphaL + alphaR)) ...
         + 2 * exp(1i*(3*theta - alphaL + alphaR)) * t2L * t2R ...
         + t1L * exp(1i*(4*theta + alphaL + alphaR)) * t2R ) ...
       - 2 * exp(2*1i*theta) * (exp(1i*theta) - 1)^2 * ...
         ( (dLD*dRU + dLU*dRD + d1D*d1U + (epsD - epsU)^2/2) * t2R * t1R ...
         - (d1U*dRD + d1D*dRU)^2 / 2 );

    g1 = -(t1R*t2R - dRD*dRU) * ...
         ( -t2R * (epsU - epsD) * exp(1i*(theta - alphaR)) ...
         + 2 * (d1U*dRD + d1D*dRU) * exp(1i*theta) ...
         + t1R * (epsU - epsD) * exp(1i*(theta + alphaR)) ) ...
         * (exp(1i*theta) - 1)^2 * (exp(1i*theta) + 1);

    g0 = (t2R*t1R - dRD*dRU) * (exp(1i*theta) - 1)^2 * ...
         ( (t2R*t1R - dRD*dRU) * (exp(2*1i*theta) + 1) ...
         - ( t2R^2 * exp(-2*1i*alphaR) ...
           + t1R^2 * exp( 2*1i*alphaR) ...
           + 2*dRD*dRU ) * exp(1i*theta) );

    p_z8 = [g8, g7, g6, g5, g4, g3, g2, g1, g0];
    z_roots = roots(p_z8);     
    if numel(z_roots) ~= 8
        continue;
    end
    if ~first_valid
        [~, idx0] = sort(angle(z_roots));
        z_prev = z_roots(idx0);
        z_branch(:, j) = z_prev;
        first_valid = true;
    else
        z_ordered = zeros(8, 1);
        used = false(8, 1);
        for k = 1:8
            d = abs(z_roots - z_prev(k));
            d(used) = Inf;          
            [~, idx_min] = min(d);
            z_ordered(k) = z_roots(idx_min);
            used(idx_min) = true;
        end
        z_branch(:, j) = z_ordered;
        z_prev = z_ordered;
    end
    for k = 1:numel(z_roots)
        beta_curr = z_roots(k);
        if abs(beta_curr) < 1e-6 || abs(beta_curr) > 1e6, continue; end
        c2 = 1; 
        c1 = -epsD - epsU + (-t2R*exp(-1i*alphaR) - t1R*exp(1i*alphaR) )/beta_curr ...
             + (-t2L*exp(-1i*alphaL) - t1L*exp(1i*alphaL) )*beta_curr;
        c0 = ( ...
             exp(-1i*(alphaL - alphaR)) * beta_curr^2 * t1R * t2L + ...
             exp(1i*(alphaL - alphaR)) * beta_curr^2 * t1L * t2R + ...
             exp(-1i*alphaL) * beta_curr^3 * t2L * epsU + ...
             exp(-1i*alphaR) * beta_curr * t2R * epsU + ...
             exp(1i*alphaL) * beta_curr^3 * t1L * epsD + ...
             exp(1i*alphaR) * beta_curr * t1R * epsD + ...
             (t1L*t2L - dLD*dLU) * beta_curr^4 + ...
             (-d1U*dLD - d1D*dLU) * beta_curr^3 + ...
             (-d1U*d1D - dLD*dRU - dLU*dRD + epsD*epsU) * beta_curr^2 + ...
             (-d1U*dRD - d1D*dRU) * beta_curr - ...
             dRD*dRU + t1R*t2R ...
             ) / beta_curr^2;
        Ej_candidates = roots([c2, c1, c0]); 
        for m = 1:numel(Ej_candidates)
            E_test = Ej_candidates(m);    
            p_verify = [ (t1L*t2L - dLD*dLU), ...
                (-t2L*(E_test-epsU)*exp(-1i*alphaL) - t1L*(E_test-epsD)*exp(1i*alphaL) - d1U*dLD - d1D*dLU), ...
                (exp(-1i*(alphaL-alphaR))*t1R*t2L   + exp(1i*(alphaL-alphaR))*t1L*t2R + E_test^2 + (-epsD-epsU)*E_test - d1D*d1U - dLD*dRU - dLU*dRD + epsU*epsD), ...
                (-t2R*(E_test-epsU)*exp(-1i*alphaR) - t1R*(E_test-epsD)*exp(1i*alphaR) - d1U*dRD - d1D*dRU), ...
                (t1R*t2R - dRD*dRU)];
            all_betas = roots(p_verify);
            all_mags = abs(all_betas);
            mags_sorted = sort(all_mags);
            condition_GBZ = abs(mags_sorted(2) - mags_sorted(3)) < 1e-6; 
            curr_mag = abs(beta_curr);
            condition_is_on_GBZ = abs(curr_mag - mags_sorted(2)) < 1e-6 || ...
                                  abs(curr_mag - mags_sorted(3)) < 1e-6;
            if condition_GBZ && condition_is_on_GBZ
                GBZ_points = [GBZ_points; beta_curr]; 
                E_points = [E_points; E_test];
                z = beta_curr; 
                H_ab_z = d1U + dRU/z + z*dLU;
                H_aa_z = epsU + t1R*exp(alphaR*1i)/z + z*t1L*exp(alphaL*1i);
                M_val = H_ab_z / (E_test - H_aa_z);
                M_GBZ = [M_GBZ; M_val];
            end
        end
    end
end
zk1 = z_branch(1, :);
zk2 = z_branch(2, :);
zk3 = z_branch(3, :);
zk4 = z_branch(4, :);
zk5 = z_branch(5, :);
zk6 = z_branch(6, :);
zk7 = z_branch(7, :);
zk8 = z_branch(8, :);

%% NUMER GBZ
all_betas_middle = [];  
for j = 1:length(eNum)
    EEj = eNum(j);
    pp = [(t1L*t2L - dLD*dLU), ...
         (-t2L*(EEj - epsU)*exp(-1i*alphaL) ...
       -t1L*(EEj - epsD)*exp(1i*alphaL) ...
       -d1U*dLD - d1D*dLU), ...
        (exp(-1i*(alphaL - alphaR))*t1R*t2L ...
       + exp( 1i*(alphaL - alphaR))*t1L*t2R ...
       + EEj^2 + (-epsD - epsU)*EEj ...
       - d1D*d1U - dLD*dRU - dLU*dRD + epsU*epsD), ...
         (-t2R*(EEj - epsU)*exp(-1i*alphaR) ...
       -t1R*(EEj - epsD)*exp(1i*alphaR) ...
       -d1U*dRD - d1D*dRU), ...
         t1R*t2R - dRD*dRU];
    beta_roots = roots(pp);
    [~,ids] = sort(abs(beta_roots)); 
    beta2 = beta_roots(ids(2));
    beta3 = beta_roots(ids(3));
    if abs(abs(beta2) - abs(beta3)) < 0.1
        all_betas_middle = [all_betas_middle; beta2; beta3];
    end
end

eD = epsD;eU = epsU;aL = alphaL;aR = alphaR;
denomL = t1L*t2L - dLD*dLU;
denomR = t1R*t2R - dRD*dRU;
r = (denomR / denomL)^(1/4);
p1 = 2 * r^2 * ( t1L*exp(1i*aL)*t2L*exp(-1i*aL) - dLD*dLU);
p2 = - t2R*exp(-1i*aR) * t1L*exp(1i*aL) ...
- t1R*exp(1i*aR) * t2L*exp(-1i*aL) ...
+ dLU*dRD + dRU*dLD;
wR = dRD * d1U + dRU * d1D ...
         - eD * t1R * exp(aR * 1i) - t2R * exp(-1i * aR) * eU;
tauR = t2R * exp(-1i * aR) + t1R * exp(aR * 1i);
wL = dLU * d1D + d1U * dLD ...
         - eD * t1L * exp(aL * 1i) - eU * t2L * exp(-1i * aL);
tauL = t2L * exp(-1i * aL) + t1L * exp(aL * 1i);
T = (p2^2 - p1^2) / p1;
lam0 = -T - (tauR * tauL) * p2 / p1 ...
          - 0.5 * r^2 * tauL^2 - 0.5 * tauR^2 / r^2;

lam1 = (eU + eD) * T - (tauL * wR + tauR * wL) * p2 / p1 ...
          - wR * tauR / r^2 - wL * tauL * r^2;

lam2 = (d1D * d1U - eD * eU) * T - wL * wR * p2 / p1 ...
          - 0.5 * wR^2 / r^2 - 0.5 * wL^2 * r^2;
discE = lam1^2 - 4*lam0*lam2;
E1 = (-lam1 + sqrt(discE)) / (2*lam0);
E2 = (-lam1 - sqrt(discE)) / (2*lam0);
[b11, b12, b13, b14] = compute_beta(E1, t1L, t2L, dLD, dLU, epsU, epsD, alphaL, d1D, d1U, t1R, t2R, alphaR, dRD, dRU);
[b21, b22, b23, b24] = compute_beta(E2, t1L, t2L, dLD, dLU, epsU, epsD, alphaL, d1D, d1U, t1R, t2R, alphaR, dRD, dRU);

chi1 = t1L * exp(1i * alphaL) * dRD - t1R * exp(1i * alphaR) * dLD;
chi2 = t1L * exp(1i * alphaL) * t2R * exp(-1i * alphaR) ...
     - t1R * exp(1i * alphaR) * t2L * exp(-1i * alphaL) ...
     + dLU * dRD - dRU * dLD;
chi3 = dLU * t2R * exp(-1i * alphaR) - dRU * t2L * exp(-1i * alphaL);
M_deg1 = (-chi2+sqrt(chi2^2-4*chi1*chi3))/(2*chi1);
M_deg2 = (-chi2-sqrt(chi2^2-4*chi1*chi3))/(2*chi1);

expLp = exp(1i*alphaL);   
expLn = exp(-1i*alphaL);  
expRp = exp(1i*alphaR);   
expRn = exp(-1i*alphaR); 

TL = t2L*expLn - t1L*expLp; 
TR = t2R*expRn - t1R*expRp; 
epsDif = epsD - epsU;

p4 = (d1D^2 - 4*dLD*dRD);
p3 = (-4*TL*dRD - 4*dLD*TR + 2*epsDif*d1D);
p2 = (4*dLU*dRD - 4*TL*TR + 4*dLD*dRU - 2*d1U*d1D + epsDif^2);
p1 = (4*dLU*TR + 4*TL*dRU - 2*d1U*epsDif);
p0 =  d1U^2 - 4*dLU*dRU;
M_branch_roots = roots([p4, p3, p2, p1, p0]);

%% figure5(b)
axes(ax_E); cla(ax_E); hold(ax_E, 'on');
scatter(ax_E, real(E_points), imag(E_points), 12, ...
    'MarkerFaceColor', [0.70 0.62 0.15], 'MarkerEdgeColor', 'none', ...
    'MarkerFaceAlpha', 0.60);
draw_patch_open_curve(EPBC1_plot, 1.8);
draw_patch_open_curve(EPBC2_plot, 1.8);
plot(ax_E, real(E1), imag(E1), 'ro', 'MarkerSize', 8, 'LineWidth', 1.4, 'MarkerFaceColor', 'r');
plot(ax_E, real(E2), imag(E2), 'bo', 'MarkerSize', 8, 'LineWidth', 1.4, 'MarkerFaceColor', 'b');
xlabel(ax_E, '$\mathrm{Re}(E)$', 'Interpreter', 'latex', 'FontSize', 14);
ylabel(ax_E, '$\mathrm{Im}(E)$', 'Interpreter', 'latex', 'FontSize', 14);
grid(ax_E, 'on'); box(ax_E, 'on');
xlim(ax_E, [-3 2]); ylim(ax_E, [-8 8]);
set(ax_E, 'LineWidth', 1, 'FontSize', 12, 'XColor', 'k', 'YColor', 'k');
text(ax_E, -0.18, 1.04, '(b)', 'Units', 'normalized', ...
    'Interpreter', 'latex', 'FontSize', 18, 'Color', 'k');
text(ax_E, real(E1)+0.10, imag(E1)+0.35, '$E_1$', ...
    'Interpreter', 'latex', 'FontSize', 12, 'Color', 'r');
text(ax_E, real(E2)-0.35, imag(E2)-0.55, '$E_2$', ...
    'Interpreter', 'latex', 'FontSize', 12, 'Color', 'b');

%% figure5(c)
axes(ax_beta); cla(ax_beta); hold(ax_beta, 'on');
scatter(ax_beta, real(GBZ_points), imag(GBZ_points), 8, angle(GBZ_points), 'filled', ...
    'MarkerFaceAlpha', 0.85, 'MarkerEdgeAlpha', 0.85);
colormap(ax_beta, 'jet');
scatter(ax_beta, real(all_betas_middle), imag(all_betas_middle), 9, ...
    'MarkerEdgeColor', [0 0.6 0], 'MarkerFaceColor', [0 0.6 0], ...
    'MarkerFaceAlpha', 0.12, 'MarkerEdgeAlpha', 0.35);
plot(ax_beta, real([b11 b12 b13 b14]), imag([b11 b12 b13 b14]), 'rx', ...
    'MarkerSize', 7, 'LineWidth', 1.2);
plot(ax_beta, real([b21 b22 b23 b24]), imag([b21 b22 b23 b24]), 'bx', ...
    'MarkerSize', 7, 'LineWidth', 1.2);
unit_circle = exp(1i*linspace(0,2*pi,200));
plot(ax_beta, real(unit_circle), imag(unit_circle), 'k--', 'LineWidth', 0.8);
xlabel(ax_beta, '$\mathrm{Re}(\beta)$', 'Interpreter', 'latex', 'FontSize', 14);
ylabel(ax_beta, '$\mathrm{Im}(\beta)$', 'Interpreter', 'latex', 'FontSize', 14);
grid(ax_beta, 'on'); box(ax_beta, 'on');
xlim(ax_beta, [-1.8 1.3]); ylim(ax_beta, [-1.2 1.2]);
set(ax_beta, 'LineWidth', 1, 'FontSize', 12, 'XColor', 'k', 'YColor', 'k');
text(ax_beta, -0.085, 1.04, '(c)', 'Units', 'normalized', ...
    'Interpreter', 'latex', 'FontSize', 18, 'Color', 'k');
tol = 1e-6;
beta1 = [b11, b12, b13, b14];
[~, ix1] = sort(abs(beta1));
for i = 1:4
    pt = beta1(ix1(i));
    M_val = (d1U + dRU/pt + pt*dLU) / ...
            (E1 - epsU - t1R*exp(alphaR*1i)/pt - pt*t1L*exp(alphaL*1i));
    dist1 = abs(M_val - M_deg1);
    dist2 = abs(M_val - M_deg2);
    if dist1 < tol && dist1 < dist2
        label = sprintf('$\\beta_{%d}(M_1)$', i);
    elseif dist2 < tol && dist2 < dist1
        label = sprintf('$\\beta_{%d}(M_2)$', i);
    else
        label = sprintf('$\\beta_{%d}$', i);
    end
    text(ax_beta, real(pt)+0.08, imag(pt)+0.08, label, ...
        'Interpreter', 'latex', 'FontSize', 12, 'Color', 'red');
end
beta2 = [b21, b22, b23, b24];
[~, ix2] = sort(abs(beta2));
for i = 1:4
    pt = beta2(ix2(i));
    M_val = (d1U + dRU/pt + pt*dLU) / ...
            (E2 - epsU - t1R*exp(alphaR*1i)/pt - pt*t1L*exp(alphaL*1i));
    dist1 = abs(M_val - M_deg1);
    dist2 = abs(M_val - M_deg2);
    if dist1 < tol && dist1 < dist2
        label = sprintf('$\\beta_{%d}(M_1)$', i);
    elseif dist2 < tol && dist2 < dist1
        label = sprintf('$\\beta_{%d}(M_2)$', i);
    else
        label = sprintf('$\\beta_{%d}$', i);
    end
    text(ax_beta, real(pt)+0.08, imag(pt)+0.08, label, ...
        'Interpreter', 'latex', 'FontSize', 12, 'Color', 'blue');
end

%% figure5(d) 
axes(ax_M); cla(ax_M); hold(ax_M, 'on');
scatter(ax_M, real(M_GBZ), imag(M_GBZ), 8, angle(M_GBZ), 'filled', ...
    'MarkerFaceAlpha', 0.85, 'MarkerEdgeAlpha', 0.85);
colormap(ax_M, 'jet');
plot(ax_M, real(M_deg1), imag(M_deg1), 'b+', 'MarkerSize', 8, 'LineWidth', 1.2);
plot(ax_M, real(M_deg2), imag(M_deg2), 'r+', 'MarkerSize', 8, 'LineWidth', 1.2);
plot(ax_M, real(M_branch_roots), imag(M_branch_roots), 'r*', 'MarkerSize', 8, 'LineWidth', 1.0);
xlabel(ax_M, '$\mathrm{Re}(M)$', 'Interpreter', 'latex', 'FontSize', 14);
ylabel(ax_M, '$\mathrm{Im}(M)$', 'Interpreter', 'latex', 'FontSize', 14);
grid(ax_M, 'on'); box(ax_M, 'on');
xlim(ax_M, [-9 18]); ylim(ax_M, [-4.2 4]);
set(ax_M, 'LineWidth', 1, 'FontSize', 12, 'XColor', 'k', 'YColor', 'k');
text(ax_M, -0.085, 1.04, '(d)', 'Units', 'normalized', ...
    'Interpreter', 'latex', 'FontSize', 18, 'Color', 'k');
text(ax_M, real(M_deg1)+0.15, imag(M_deg1)+0.15, '$M_1$', ...
    'Interpreter', 'latex', 'FontSize', 12, 'Color', 'b');
text(ax_M, real(M_deg2)+0.15, imag(M_deg2)+0.15, '$M_2$', ...
    'Interpreter', 'latex', 'FontSize', 12, 'Color', 'r');
text(ax_M, 0.56, 0.82, '$W_1=\mathrm{mod}_2(1+2-0)=1$', 'Units', 'normalized', ...
    'Interpreter', 'latex', 'FontSize', 14, 'Color', 'b');
text(ax_M, 0.56, 0.66, '$W_2=\mathrm{mod}_2(1+1-0)=0$', 'Units', 'normalized', ...
    'Interpreter', 'latex', 'FontSize', 14, 'Color', 'r');

set([ax_phase ax_E ax_beta ax_M], 'TickDir', 'in', 'Layer', 'top');
drawnow;
exportgraphics(fig5, fullfile(pwd, 'figure5_grouped.png'), 'Resolution', 300);
savefig(fig5, fullfile(pwd, 'figure5_grouped.fig'));
function [beta1, beta2, beta3, beta4] = compute_beta(E, t1L, t2L, dLD, dLU, epsU, epsD, alphaL, d1D, d1U, t1R, t2R, alphaR, dRD, dRU)
     den = t1L * t2L - dLD * dLU;            
    a3 = (-t2L * (E - epsU) * exp(-1i*alphaL) - t1L * (E - epsD) * exp(1i*alphaL) - d1U*dLD - d1D*dLU) / den;
    a2 = (exp(-1i*(alphaL-alphaR)) * t1R * t2L + exp(1i*(alphaL-alphaR)) * t1L * t2R ...
          + E^2 + (-epsD-epsU)*E - d1D*d1U - dLD*dRU - dLU*dRD + epsU*epsD) / den;
    a1 = (-t2R * (E - epsU) * exp(-1i*alphaR) - t1R * (E - epsD) * exp(1i*alphaR) - d1U*dRD - d1D*dRU) / den;
    Y  = (exp(-1i*(alphaL-alphaR)) * t1R * t2L + exp(1i*(alphaL-alphaR)) * t1L * t2R - dLD*dRU - dLU*dRD) / den;
    
    K = sqrt(a3^2/4 - a2 + Y);
    alpha0 = a3/2;
    A1 = sqrt(3*a3^2/4 - K^2 - 2*a2 + (4*a3*a2 - 8*a1 - a3^3) / (4*K));
    A2 = sqrt(3*a3^2/4 - K^2 - 2*a2 - (4*a3*a2 - 8*a1 - a3^3) / (4*K)); 

    beta1 = -(alpha0 - K - A1)/2;
    beta2 = -(alpha0 - K + A1)/2;
    beta3 = -(alpha0 + K - A2)/2;
    beta4 = -(alpha0 + K + A2)/2;
end

function z_out = break_large_jumps(z_in, fac)
    
    z_out = z_in;
    dz = abs(diff(z_in));
    dz_valid = dz(isfinite(dz) & dz > 0);

    if isempty(dz_valid)
        return;
    end

    thr = fac * median(dz_valid);
    bad = find(dz > thr);

    for ii = 1:numel(bad)
        z_out(bad(ii)+1) = NaN;
    end
end

function draw_patch_open_curve(z, lw)
    z = z(:);
    M1 = 6000; 

    c_all = linspace(0,1,M1);
    c_all = [c_all, c_all(2:end)]; 
    c_all = c_all(1:numel(z)).';

    isBreak = isnan(z);
    start_idx = [1; find(isBreak)+1];
    end_idx   = [find(isBreak)-1; numel(z)];

    valid_block = start_idx <= end_idx;
    start_idx = start_idx(valid_block);
    end_idx   = end_idx(valid_block);

    for b = 1:numel(start_idx)
        ids = start_idx(b):end_idx(b);
        if numel(ids) < 2, continue; end
        zb = z(ids);
        xb = real(zb); yb = imag(zb); cb = c_all(ids);
        vertices = [xb, yb, zeros(numel(zb),1)];
        faces = [(1:numel(zb)-1)', (2:numel(zb))'];
        patch('Vertices', vertices, 'Faces', faces, ...
              'FaceVertexCData', cb, 'FaceColor', 'none', ...
              'EdgeColor', 'interp', 'LineWidth', lw);
    end
end
